### ISSUE TITLE
Add a toastify notification toasts

### ISSUE THREAD

**Issue by himanishu-2512** [himanishu-2512/Project-XYZ#28]
[Link for toastify](https://youtu.be/k70cqeQGrHQ)

**Comment by JesusC-R** [comment]
Please describe where the notification should be added

**Comment by himanishu-2512** [comment]
> Please describe where the notification should be added

Actually we are looking to create these notifictions toasts in login /Signup Page. That is in [src/Pages/LoginForm](https://github.com/himanishu-2512/Project-XYZ/blob/master/src/Pages/LoginForm.js)
 For the refernce of toastify you can follow this[npm-package of toastify](https://www.npmjs.com/package/react-toastify).

**Comment by himanishu-2512** [comment]
> Please describe where the notification should be added

If you're going to work on it, let me know so I can assign you this issue.

**Comment by JesusC-R** [comment]
I’d like to
