### ISSUE TITLE
Add interactivity to the Posts and Questions layout

### ISSUE THREAD

**Issue by misterprakhar** [himanishu-2512/Project-XYZ#39]
**Is your feature request related to a problem? Please describe.**
The user should be able to view anyone's profile by clicking on their profile photo on the posts or questions they have posted. Also the three dot menu on the posts should provide the user with options.

**Describe the solution you'd like**
On clicking the profile photo or the author's name on a post, it should redirect to the profile page of the post's author.

On clicking the three dot menu, the user should have the option to Share the post, and if it is the user's own post, Edit & Delete options should also be available.

**Comment by asif158** [comment]
I'm interested
