### ISSUE TITLE
Style the scroll bar

### ISSUE THREAD

**Issue by misterprakhar** [himanishu-2512/Project-XYZ#40]
**Is your feature request related to a problem? Please describe.**
The current scroll bar is the default version which doesn't look very good.

**Describe the solution you'd like**
Make the scroll bar slimmer and style it similar to the photo below.

![image](https://github.com/himanishu-2512/Project-XYZ/assets/82384669/937f48c7-6e66-4f83-becc-1be68ba95bc2)

**Comment by asif158** [comment]
Assign this to me I am interested.
