### ISSUE TITLE
Add Skeleton preview on Feed

### ISSUE THREAD

**Issue by misterprakhar** [himanishu-2512/Project-XYZ#70]
**Is your feature request related to a problem? Please describe.**
When the feed is being loaded, the page stays blank until the complete feed is fetched. 

**Describe the solution you'd like**
Add a skeleton preview on the homepage and also on the Posts & Saved sections on the profile page.

**Comment by asif158** [comment]
I am interested.

**Comment by misterprakhar** [comment]
Design the skeleton for Profile page too.

**Comment by asif158** [comment]
Okay, I'll work on it.
